import type { Block } from 'payload'

const priceMenuItemsField = (name: string, label: string, defaultValue?: { label: string; price: string }[]) => ({
  name,
  label,
  type: 'array' as const,
  required: true,
  fields: [
    {
      name: 'label',
      type: 'text' as const,
      required: true,
    },
    {
      name: 'price',
      type: 'text' as const,
      required: true,
    },
  ],
  defaultValue,
})

export const PriceMenu: Block = {
  slug: 'priceMenu',
  interfaceName: 'PriceMenuBlock',
  fields: [
    {
      name: 'headingTop',
      type: 'text',
      localized: true,
      required: true,
      defaultValue: 'GINGER PRODUCTS',
    },
    {
      name: 'brandTitle',
      type: 'text',
      localized: true,
      required: true,
      defaultValue: 'GINGERS',
    },
    {
      name: 'brandSubtitle',
      type: 'text',
      localized: true,
      required: true,
      defaultValue: 'HOT FRESH & SPICY',
    },
    {
      name: 'headingMenu',
      type: 'text',
      localized: true,
      required: true,
      defaultValue: 'PROIZVODI OD ĐUMBIRA',
    },
    {
      type: 'collapsible',
      label: 'Price list by locale',
      fields: [
        priceMenuItemsField('items_en', 'Items (English)', [
          { label: '100% Ginger Essence', price: '1000 RSD' },
          { label: 'Ginger Drink', price: '350 RSD' },
          { label: 'Ginger Drink 3l', price: '900 RSD' },
          { label: 'Ginger Syrup', price: '600 RSD' },
          { label: 'Ginger Erythritol Syrup 1l', price: '1300 RSD' },
          { label: 'Ginger Erythritol Syrup 0.33l', price: '500 RSD' },
          { label: 'Ginger Wine 1l', price: '1000 RSD' },
          { label: 'Small Ginger Wine 0.25l', price: '300 RSD' },
          { label: 'Ginger Garlic (Small)', price: '200 RSD' },
          { label: 'Ginger Garlic (Medium)', price: '400 RSD' },
          { label: 'Ginger Garlic (Large)', price: '600 RSD' },
          { label: 'Ginger Honey – Small Jar', price: '750 RSD' },
          { label: 'Ginger Honey – Large Jar', price: '1500 RSD' },
          { label: 'Ginger Seedling', price: '500 RSD' },
          { label: 'Ginger Beer 1l', price: '300 RSD' },
        ]),
        priceMenuItemsField('items_sr', 'Items (Serbian)', [
          { label: 'Ginger Esencija', price: '1000 RSD' },
          { label: 'Ginger Napitak', price: '350 RSD' },
          { label: 'Ginger Napitak 3l', price: '900 RSD' },
          { label: 'Ginger Sirup', price: '600 RSD' },
          { label: 'Ginger Eritritol Sirup 1L', price: '1300 RSD' },
          { label: 'Ginger Eritritol Sirup 0.33L', price: '500 RSD' },
          { label: 'Ginger Vino 1L', price: '1000 RSD' },
          { label: 'Small Ginger Wine 0.25L', price: '300 RSD' },
          { label: 'Ginger Garlic (Mali)', price: '200 RSD' },
          { label: 'Ginger Garlic (Srednji)', price: '400 RSD' },
          { label: 'Ginger Garlic (Veliki)', price: '600 RSD' },
          { label: 'Ginger Honey – Mala Tegla', price: '750 RSD' },
          { label: 'Ginger Honey – Velika Tegla', price: '1500 RSD' },
          { label: 'Ginger Sadnica', price: '500 RSD' },
          { label: 'Ginger Pivo 1L', price: '300 RSD' },
      ]),
        priceMenuItemsField('items_hu', 'Items (Hungarian)', [
          { label: '100% gyömbér esszencia', price: '1000 RSD' },
          { label: 'Gyömbérital', price: '350 RSD' },
          { label: 'Gyömbérital 3 l', price: '900 RSD' },
          { label: 'Gyömbérszirup', price: '600 RSD' },
          { label: 'Gyömbér–eritrit szirup 1 l', price: '1300 RSD' },
          { label: 'Gyömbér–eritrit szirup 0,33 l', price: '500 RSD' },
          { label: 'Gyömbérbor 1 l', price: '1000 RSD' },
          { label: 'Kis gyömbérbor 0,25 l', price: '300 RSD' },
          { label: 'Gyömbér–fokhagyma (kicsi)', price: '200 RSD' },
          { label: 'Gyömbér–fokhagyma (közepes)', price: '400 RSD' },
          { label: 'Gyömbér–fokhagyma (nagy)', price: '600 RSD' },
          { label: 'Gyömbéres méz – kis üveg', price: '750 RSD' },
          { label: 'Gyömbéres méz – nagy üveg', price: '1500 RSD' },
          { label: 'Gyömbérpalánta', price: '500 RSD' },
          { label: 'Gyömbérsör 1 l', price: '300 RSD' },
        ]),
        priceMenuItemsField('items_ru', 'Items (Russian)', [
          { label: '100% имбирная эссенция', price: '1000 RSD' },
          { label: 'Имбирный напиток', price: '350 RSD' },
          { label: 'Имбирный напиток 3 л', price: '900 RSD' },
          { label: 'Имбирный сироп', price: '600 RSD' },
          { label: 'Имбирный сироп с эритритом 1 л', price: '1300 RSD' },
          { label: 'Имбирный сироп с эритритом 0,33 л', price: '500 RSD' },
          { label: 'Имбирное вино 1 л', price: '1000 RSD' },
          { label: 'Имбирное вино (малое) 0,25 л', price: '300 RSD' },
          { label: 'Имбирь с чесноком (малый)', price: '200 RSD' },
          { label: 'Имбирь с чесноком (средний)', price: '400 RSD' },
          { label: 'Имбирь с чесноком (большой)', price: '600 RSD' },
          { label: 'Имбирный мёд — маленькая банка', price: '750 RSD' },
          { label: 'Имбирный мёд — большая банка', price: '1500 RSD' },
          { label: 'Саженец имбиря', price: '500 RSD' },
          { label: 'Имбирное пиво 1 л', price: '300 RSD' },
        ]),
      ],
    },
    {
      name: 'footerLeft',
      type: 'text',
      localized: true,
      required: true,
      defaultValue: 'www.gingers.rs',
    },
    {
      name: 'footerRight',
      type: 'text',
      localized: true,
      required: true,
      defaultValue: '061 644 3707',
    },
  ],
  labels: {
    plural: 'Price Menus',
    singular: 'Price Menu',
  },
}